// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCmC_MF5-4son8aTfZDw5OwsmDDa1oMTI',
    appId: '1:871625611142:web:423f5e6a6c6d9c6aa1fe07',
    messagingSenderId: '871625611142',
    projectId: 'mytp2-44ee9',
    authDomain: 'mytp2-44ee9.firebaseapp.com',
    storageBucket: 'mytp2-44ee9.firebasestorage.app',
    measurementId: 'G-132WW5KY2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapSosCv-fCvt-nVJ01GUbps1gyYc6GEg',
    appId: '1:871625611142:android:9ae1d050a3b0dad7a1fe07',
    messagingSenderId: '871625611142',
    projectId: 'mytp2-44ee9',
    storageBucket: 'mytp2-44ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBf4BOSEqYgdcP72WMj1E91DAhMfQem3c',
    appId: '1:871625611142:ios:a32713bdc81bc878a1fe07',
    messagingSenderId: '871625611142',
    projectId: 'mytp2-44ee9',
    storageBucket: 'mytp2-44ee9.firebasestorage.app',
    iosClientId: '871625611142-eqfrcjpbotbb174j4anpd9fh4ho9uos4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBf4BOSEqYgdcP72WMj1E91DAhMfQem3c',
    appId: '1:871625611142:ios:a32713bdc81bc878a1fe07',
    messagingSenderId: '871625611142',
    projectId: 'mytp2-44ee9',
    storageBucket: 'mytp2-44ee9.firebasestorage.app',
    iosClientId: '871625611142-eqfrcjpbotbb174j4anpd9fh4ho9uos4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCmC_MF5-4son8aTfZDw5OwsmDDa1oMTI',
    appId: '1:871625611142:web:6c539404fb1ea53ea1fe07',
    messagingSenderId: '871625611142',
    projectId: 'mytp2-44ee9',
    authDomain: 'mytp2-44ee9.firebaseapp.com',
    storageBucket: 'mytp2-44ee9.firebasestorage.app',
    measurementId: 'G-0CFWM6YT9L',
  );
}
